
import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';
import Header from '@/components/Header';
import { QUERY,hygraph } from '@/service';
import { Button } from 'flowbite-react';
import Link from 'next/link';
import Server from 'next/dist/server/base-server';

const inter = Inter({ subsets: ['latin'] });

export default  function Home() {

console.log(process.browser)


  return (
    <>
      <Head>
        <title>Havas-Case-Study</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='flex h-fit flex-col justify-between bg-bgMain '>
        <Header />
        <div className='h-screen flex gap-5 justify-center items-center mt-auto w-full pb-20 '>
          <Link href='/csr'>
            <Button className=' font-roboto' color='gray'>
              CSR
            </Button>
          </Link>
          <Link href='/ssg'>
            <Button className='font-roboto' color='gray'>
              SSG
            </Button>
          </Link>
          <Link href='/ssr'>
            <Button className='font-roboto' color='gray'>
              SSR
            </Button>
          </Link>
        </div>
      </main>
    </>
  );
}
